server:
  servlet:
    context-path: /istatproxy
      
  port:  ${PORT:5000}

logging:
  file: ${APP_HOME:${user.home}/istatproxy/istatproxy.log}

  

spring:
  application:
    name: istatproxy


it:
  istat:
    proxy:
      sourceUrl: https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.xls
      digestXls: MD5
      dateFormatter: ddMMyyyy
      xlsname: elenco-comuni-italiani.xls
      xlsSoppressi: elenco-comuni-soppressi.xls
      localPath: ${APP_HOME:${user.home}/istatproxy/}
      version-number: v0.5-20180713


eureka:
  client:
    serviceUrl:
      defaultZone: http://docker3-tst:8761/eureka/
      
